### ISSUE TITLE
Unexpected VM Exit with newest Win10 update

### ISSUE THREAD

**Issue by mrtiggles5** [tandasat/DdiMon#20]
Hello Tandasat, 
After the recent windows update I am having issues with loading my hypervisor. Every time I start the hypervisor's service I get a manually initiated crash, something that I haven't had problems with before. 
After some investigating with Windbg, I found that the BSOD was caused by an unexpected Vm-Exit in VmmpHandleUnexpectedExit() during VmInitialization. 

Have you been having the same sorts of issues?

**Comment by tandasat** [comment]
Reproduced the issue and found a fix on my side. Try 1) enabling `invpcid`, and 2) filtering out the bit 63 when CR3 is updated. Those changes were already applied to HyperPlatform but not ported to DdiMon. You can, however, tentatively copy changes here: [1)](https://github.com/tandasat/HyperPlatform/commit/be1f59abb715d32b0dac3e471d0ec4337b9709cd#diff-8823c34c41b7fbb77a5212b8f130e919R595) and [2)](https://github.com/tandasat/HyperPlatform/commit/be1f59abb715d32b0dac3e471d0ec4337b9709cd#diff-8aa539026731c1fd7eebbb17cc8ae848R935) 

I will plan to rebase the `ddimon` branch of HyperPlatform to be in sync with `master` soon.

* Technical explanation in case you are interested in

The patch on Jun 3 introduced a set of changes called KPTI (Kernel Page Table Isolation, or Kernel VA Shadowing as what Microsoft calls it) for all supported x64 Windows, in order to mitigate the Meltdown vulnerability. With this patch, Windows started to use Process-Context Identifiers (PCIDs) and the bit 63 of CR3 to avoid flushing TLB and paging-structure caches for better performance, as KPTI introduced one more additional CR3 for each process, and hence, more move-to-CR3 operations which would flush TLB etc. Then, to manage PCIDs, the kernel also started to use the `invpcid` instruction.

**Comment by tandasat** [comment]
This should get fixed with 7b9f6110644dfc235c897ccb19c425733a09d61e.
