### ISSUE TITLE
Ddimon cause 100% cpu workload when loaded it in 4 cores virtual machine

### ISSUE THREAD

**Issue by kruglinski** [tandasat/DdiMon#25]
1 or 2 cores is OK,  100% cpu workload in 4 cores, Don't known what happened!

![vm](https://user-images.githubusercontent.com/2869425/49415044-6f651380-f7b0-11e8-86bf-1ab1cfdd8a46.png)
![vm](https://user-images.githubusercontent.com/2869425/49415162-c2d76180-f7b0-11e8-8ca9-fe2e89ccf16f.png)

2 two-cores cpu or 4 one-core cpu have same result!
![win7x64sp1-2018-12-04-10-29-20](https://user-images.githubusercontent.com/2869425/49415068-7e4bc600-f7b0-11e8-916b-211a0068c8b2.png)

**Comment by tandasat** [comment]
A VM can have very different characteristics from a real hardware when it comes performance of nested virtualization, so I would suggest testing on a real hardware and see you observe the same performance degradation if performance on a real hardware is actual concern. On my testing, I did not see that.  

Also, you can measure which functions are slow with `HYPERPLATFORM_PERFORMANCE_MEASURE_THIS_SCOPE` macros in the scope granularity. I suggest you to take numbers on both 2 and 4 logical core machines, and compare them. 

While I wish to make this project as performant as possible, I do not plan to actively work on this issue as performance is not a priority. If you can take data, I can perhaps assist you to find the root cause and a fix, however.

**Comment by kruglinski** [comment]
I tested on real hardware, ddimon works fine! so I assume that there are some bugs in vmware
