### ISSUE TITLE
BSODing with stop code: UNEXPECTED KERNEL MODE TRAP

### ISSUE THREAD

**Issue by hxdxs** [tandasat/DdiMon#27]
Hey, the moment I inject my DLL and attempt to hook, my pc crashes with this stop code: UNEXPECTED KERNEL MODE TRAP. 

I'm using Windows 10, Version 1803 (OS Build 17134.523) HOME x64

Things I've checked: 

VT-x enabled, triple-checked that and used programs such as Speccy, LeoMoon CPU-V and Task Manager self to check if virtualization is enabled, and it is! 
DEP enabled for all programs
Testmode enabled, Build 17134.rs4_release.180410-1804 

The driver has been modified a bit, so it fits our needs (it will stay private, won't be distributed and all credits go to "tandasat"). 

Driver starts without any problems. 

Andddddd, here is where the witchcraft comes, the same DLL works on my friend's pc without any problems, injecting into the same process using the same injector. He is also on Windows 10, Version 1803 (OS Build 17134.523) PRO x64, note that he is on PRO and I'm on HOME (Home doesn't have to access to Hyper-V, maybe the reason?).

Here is the crash dump analyze for it, used latest version Windbg.exe: 

[CrashDump.txt](https://github.com/tandasat/DdiMon/files/2783866/CrashDump.txt)

Appreciate any kind of help.

**Comment by tandasat** [comment]
This is very hard to say what could be wrong there since I have no idea what changes are made. I would recommend attaching a debugger and trying to know when and how the exception happens if possible (eg, try to repro the issue in a VM). If a debugger is not an option, probably adding more logs and analyzing them in a DMP file is what I would do. Also, as a general troubleshooting technique, you could test with old versions and try to see which code (revision / functionality) is causing the issue. Good luck!

By the way, you should get credit for your work :)
